#pragma config(Sensor, S1,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     touchSensor,    sensorEV3_Touch)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//declaring variables
	int light, dark;
	float threshold;


	//display options for white
	while (getButtonPress(buttonEnter) == 0)
	{
		displayBigTextLine(1, "Press enter");
		displayBigTextLine(3, "button when");
		displayBigTextLine(5, "over white");
	}//end while

	light = SensorValue(colorSensor);

	eraseDisplay();

	displayBigTextLine(4, "White is %d", light);
	sleep(2000);

	eraseDisplay();

	//display options for black
	while (getButtonPress(buttonEnter) == 0)
	{
		displayBigTextLine(1, "Press enter");
		displayBigTextLine(3, "button when");
		displayBigTextLine(5, "over black");
	}//end while

	dark = SensorValue(colorSensor);

	eraseDisplay();

	//display how dark it is
	displayBigTextLine(4, "Black is %d", dark);
	sleep(2000);

	//find threshold
	threshold = (light + dark) / 2.0;

	//display threshold
	displayBigTextLine(4, "The threshold");
	displayBigTextLine(6, "is %.3f", threshold);
	sleep(2000);
}//end main
