#pragma config(Sensor, S1,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S3,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     touchSensor,    sensorEV3_Touch)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int i;

	//loop 4 times in order to make a square and use less lines than writing it four times
	for(i=0; i<4; i++)
	{
		//move forwards at half speed
		setMotorSpeed(motorC, 50);
		setMotorSpeed(motorB, 50);
		sleep(2000);

		//Resets the gyro on port 2 to 0 degrees
		resetGyro(S2);

		//Keep looping until the gyro sensor reads greater
		//than 90 degrees from its current position
		repeatUntil(getGyroDegrees(S2) > 72)		/*Due to a sensor inaccuracy we must have the value as
																						72 in order for it to turn 90 degrees*/
		{
			//Point turn to the left
			setMotorSpeed(motorC, -30);
			setMotorSpeed(motorB, 30);

		}//end repeamotorC

	}//end for

}//end main
