#pragma config(Sensor, S1,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S3,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     touchSensor,    sensorEV3_Touch)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
		//Resets the gyro on port 2 to 0 degrees
		resetGyro(S2);

		//Keep looping until the gyro sensor reads greater
		//than 90 degrees from its current position

	repeatUntil (getButtonPress(buttonEnter) == 1)
		{
			while(getGyroDegrees(S2) != 0)
			{
				//Point turn to the left
				setMotorSpeed(motorC, getGyroDegrees(S2)/2);
				setMotorSpeed(motorB, getGyroDegrees(S2)/2);
			}
		}
}//end main
