#pragma config(Sensor, S1,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S3,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     touchSensor,    sensorEV3_Touch)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//reset gyro sensor value
	resetGyro(S2);

	setMotorSpeed(motorA, 5);
	sleep(500);
	setMotorSpeed(motorA, -5);
	sleep(500);

	while(getGyroDegrees(S2) > 5)
	{
		setMotorSpeed(motorA, 10);
		setMotorSpeed(motorB, getGyroDegrees(S2));
		setMotorSpeed(motorC, getGyroDegrees(S2));
	}//end if

	while(getGyroDegrees(S2) < 5)
	{
		setMotorSpeed(motorA, -5);
		setMotorSpeed(motorB, getGyroDegrees(S2));
		setMotorSpeed(motorC, getGyroDegrees(S2));
	}//end if

}//end main
