#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  Lab1-thereandbackagain.c


This program will move your robot forward for 5 seconds. once 5 seconds is over the robot will turn 180 degrees and then travel back
  the same direction for another 5 seconds.

                            ROBOT CONFIGURATION: LEGO EV3 REM Bot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    MotorC        			leftMotor           LEGO EV3 Motor		      Left side motor
    MotorB       				rightMotor          LEGO EV3 Motor		      Right side motor (reversed)
------------------------------------------------------------------------------------------------*/

task main()
{
	setMotorSpeed(leftMotor, 50);		//Set the leftMotor (motor1) to half power (50)
	setMotorSpeed(rightMotor, 50);  //Set the rightMotor (motor6) to half power (50)
	sleep(5000);										//Wait for 5 seconds before continuing on in the program.

	setMotorSpeed(leftMotor, -50);		//Set the leftMotor (motor1) to full power reverse (-100)
	setMotorSpeed(rightMotor, 50);  	//Set the rightMotor (motor6) to full power forward (100)
	sleep(700);											//Wait for 1 second before continuing on in the program.

	setMotorSpeed(leftMotor, 50);		//Set the leftMotor (motor1) to half power (50)
	setMotorSpeed(rightMotor, 50);  //Set the rightMotor (motor6) to half power (50)
	sleep(5000);										//Wait for 5 seconds before continuing on in the program.


}
