#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  Lab1-squareroute.c


This program will move your robot make a series of moves for different lengths of time.
  At the end of the program, all motors will shut down automatically and turn off.

                            ROBOT CONFIGURATION: LEGO EV3 REM Bot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                [Description]
    MotorC        	leftMotor           LEGO EV3 Motor	  Left side motor
    MotorB       	rightMotor          LEGO EV3 Motor	  Right side motor (reversed)
------------------------------------------------------------------------------------------------*/



task main()
{
	// Move forward at half power for 1.5 seconds
	setMotorSpeed(leftMotor, 50);	//Set the leftMotor (motor1) to half power forward (50)
	setMotorSpeed(rightMotor, 50); 	//Set the rightMotor (motor6) to half power forward (50)
	sleep(1500);			//Wait for 1.5 seconds before continuing on in the program.

	// Move forward at half power for 1.5 seconds
	setMotorSpeed(leftMotor, 0);	//Set the leftMotor (motor1) to stop (00)
	setMotorSpeed(rightMotor, 50); 	//Set the rightMotor (motor6) to half power forward (50)
	sleep(600);			//Wait for .3 seconds before continuing on in the program.

		// Move forward at half power for 1.5 seconds
	setMotorSpeed(leftMotor, 50);	//Set the leftMotor (motor1) to half power forward (50)
	setMotorSpeed(rightMotor, 50); 	//Set the rightMotor (motor6) to half power forward (50)
	sleep(1500);			//Wait for 1.5 seconds before continuing on in the program.

	// Move forward at half power for 1.5 seconds
	setMotorSpeed(leftMotor, 0);	//Set the leftMotor (motor1) to stop (00)
	setMotorSpeed(rightMotor, 50); 	//Set the rightMotor (motor6) to half power forward (50)
	sleep(650);			//Wait for .3 seconds before continuing on in the program.

	// Move forward at half power for 1.5 seconds
	setMotorSpeed(leftMotor, 50);	//Set the leftMotor (motor1) to half power forward (50)
	setMotorSpeed(rightMotor, 50); 	//Set the rightMotor (motor6) to half power forward (50)
	sleep(1500);			//Wait for 1.5 seconds before continuing on in the program.

	// Move forward at half power for 1.5 seconds
	setMotorSpeed(leftMotor, 0);	//Set the leftMotor (motor1) to stop (00)
	setMotorSpeed(rightMotor, 50); 	//Set the rightMotor (motor6) to half power forward (50)
	sleep(650);			//Wait for .3 seconds before continuing on in the program.

	// Move forward at half power for 1.5 seconds
	setMotorSpeed(leftMotor, 50);	//Set the leftMotor (motor1) to half power forward (50)
	setMotorSpeed(rightMotor, 50); 	//Set the rightMotor (motor6) to half power forward (50)
	sleep(1500);			//Wait for 1.5 seconds before continuing on in the program.

	// Move forward at half power for 1.5 seconds
	setMotorSpeed(leftMotor, 0);	//Set the leftMotor (motor1) to stop (00)
	setMotorSpeed(rightMotor, 50); 	//Set the rightMotor (motor6) to half power forward (50)
	sleep(600);			//Wait for .3 seconds before continuing on in the program.
}
