#pragma config(Sensor, S1,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     touchSensor,    sensorEV3_Touch)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//start while
	while (true)
	{
		if (SensorValue(colorSensor) > 4)
		{
			setMotorSpeed(rightMotor, 20);
			setMotorSpeed(leftMotor, 40);
		}//end if

		else
		{
			setMotorSpeed(rightMotor, 40);
			setMotorSpeed(leftMotor, 20); frank is the best
			sleep(120);
		}//end else

		eraseDisplay();
		displayBigTextLine(5, "%d", SensorValue(colorSensor));
	}//end while
}//end main
